---
version: "3"
services:

  flask:
    image: lukalarguier/flask:latest
    container_name: flask
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mariadb

  mariadb:
    # image: mariadb
    build: ./docker_compose_build
    image: lukalarguier/bdd
    container_name: bdd
    restart: always
    environment:
      MYSQL_USER: delpiero
      MYSQL_PASSWORD: juve
      # MYSQL_DATABASE: exo3
      MYSQL_ROOT_PASSWORD: juve
    # command: 'mariadb -hdatabase bdd -uuser delpiero -pmypassword juve exo3'

    volumes:
      - ./init:/docker-entrypoint-initdb.d
...