---
version: "1"
services:

  flask:
    image: lukalarguier/flask:latest


  mariadb:
    image: mariadb
    container_name: bdd
    restart: always
    depends_on:
      - flask
    environment:
      - MYSQL_USER: user
      - MYSQL_PASSWORD: juve
      - MYSQL_DATABASE: students.sql
      - MYSQL_ROOT_PASSWORD: root

    volumes:
      - ${PWD}/mariadb/:/var/lib/mysql/

    

  servicesWeb:
    image: httpd
    container_name: servicesWeb
    restart: always
    depends_on:
      - flask
    ports:
      - 5000:5000



...