---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: exo3

spec:
  type: NodePort
  selector: 
    app: flask
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31000
    protocol: TCP
...